### ISSUE TITLE
some files fail to compress

### ISSUE THREAD

**Issue by dvhassel** [GrokImageCompression/grok#334]
I'm trying to compress a series of TIF files (uncompressed, validated by JHOVE), but some files seem to fail.  I'm using these encoding parameters:

`-f -n 6 -c [256,256],[256,256],[256,256],[256,256],[256,256],[128,128] -t 256,256 -p RPCL -SOP -EPH -v -I -r 36,24,12,6,4,2`

and I suspect it has something to do with the ratios. Leaving out the ratios compresses the files just fine.

verbose output I get:
```
[2023-02-12 19:45:58.012] [warning] libtiff: Unknown field with tag 36867 (0x9003) encountered
[2023-02-12 19:45:58.014] [warning] libtiff: Unknown field with tag 36868 (0x9004) encountered
[2023-02-12 19:46:02.285] [error] failed to compress image: grk_compress
[2023-02-12 19:46:02.328] [error] failed to compress image
```

**Comment by boxerab** [comment]
Thanks for reporting. Would you mind sharing one or more of the files that fail to compress ?

**Comment by dvhassel** [comment]
sure: https://we.tl/t-Ok5btVz3bp

They are part of a series of 50+ images, all created on the same scanner, using the same settings.  All compress fine, except these 4.

**Comment by boxerab** [comment]
So, the problem here is that 

1. the final tile to be compressed is very small
2. adding SOP and EPH packet markers adds a fixed overhead to each stored packet, resulting in the compressor being unable to meet the compression ratio of 6 or 12

In this case, I disable SOP markers for this tile. If this still fails, I also disable EPH markers. Is this a reasonable solution for your work flow ?  An alternative would be to choose a smaller compression ratio.

**Comment by boxerab** [comment]
@dvhassel you can get the latest build with these fixes at

https://github.com/GrokImageCompression/grok/actions/runs/4167090214

**Comment by boxerab** [comment]
Here is the new version that will compress those files: 
 
https://github.com/GrokImageCompression/grok/actions/runs/4169633637
